### PR TITLE
#159965430 Setup redux .

### PR DESCRIPTION
**Pull request by Quantum-35**
## What does this PR do?
- Setup redux by creating store, rootReducers file that will combine all reducers.
- Add .eslintrc file to enforce js linting.

## Description of Task to be completed?
- Appropriate file structure and folder for setting up redux.
- Add eslintrc and configuration from airbnb.

## How should this be manually tested?
Clone the repo, cd into ah-leagueoflegends-frontend. Run **npm install** or **yarn add**. Then run yarn start.

## What are the relevant pivotal tracker stories?
[#159965430](https://www.pivotaltracker.com/story/show/159965430)

## Screenshot.
screen shot 2018-10-02 at 23 47 12

### CODE REVIEW

**Review by Derrickkip — APPROVED** [review]
Looks good to me

**Review by DerKip — APPROVED** [review]

**Review by kevintumbo — CHANGES_REQUESTED** [review]
- store.js is empty - configure the redux store and define the initial state
- rootReducer.js is empty - configure rootReducer with redux.
- After setting up the store expose the store to the application using a provider

**Review by Derrickkip — COMMENTED** [review]
Kindly remove the Signup and Login implementation as they are not part of the story

**Review by Derrickkip — APPROVED** [review]

**Review by Mutuba — APPROVED** [review]
Looks good!

**Review by kevintumbo — APPROVED** [review]

**Pull request merged**
